DROP TABLE IF EXISTS employee;

CREATE TABLE employee (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fname TEXT NOT NULL,
    lname TEXT NOT NULL,
    sex TEXT NOT NULL,
    job TEXT NOT NULL
);